"""
Pydantic Data Models for the Multi-Agent Poetic Council.
Defines contracts between Muse, Poet, and Arud Critic agents.
"""

from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field


class PoeticTheme(str):
    FAKHR = "فخر وحماسة"
    HIKMA = "حكمة وتأمل"
    GHAZAL = "غزل ووجدان"
    WASF = "وصف وطبيعة"
    RITHA = "رثاء وشجن"
    MODERN = "معاصرة وتقنية بلسان كلاسيكي"
    BIRR = "بر الوالدين ووجدان الأمومة"


class PoemCompositionRequest(BaseModel):
    """User request specification for poem generation."""
    topic: str = Field(description="The subject or topic requested by user (e.g. 'الذكاء الاصطناعي', 'الشجاعة')")
    theme: Optional[str] = Field(default=None, description="Optional poetic theme/purpose (غرض القصيدة)")
    target_meter: Optional[str] = Field(default=None, description="Desired meter (e.g. 'الطويل', 'الكامل', 'البسيط')")
    target_rhyme: Optional[str] = Field(default=None, description="Desired rawiyy/rhyme letter (e.g. 'ل', 'م', 'ر')")
    verse_count: int = Field(default=3, ge=1, le=10, description="Number of verses to compose")
    style_era: str = Field(default="جاهلي / عباسي", description="Linguistic era aesthetic")


class MuseInspiration(BaseModel):
    """Output generated by the Muse Agent to guide the Poet Agent."""
    topic: str
    theme: str
    selected_meter: str
    meter_tafail: str
    selected_rhyme: str
    imagery_concepts: List[str] = Field(default_factory=list)
    lexicon_metaphors: List[Dict[str, Any]] = Field(default_factory=list, description="Asas Al-Balagha rhetorical motifs")
    guidance_notes: str = ""


class VerseDraft(BaseModel):
    """A single verse consisting of Sadr and Ajuz."""
    verse_number: int
    sadr: str = Field(description="First hemistich (الصدر)")
    ajuz: str = Field(description="Second hemistich (العجز)")
    full_verse: str = Field(description="Combined formatted verse with separator")

    @classmethod
    def from_parts(cls, verse_number: int, sadr: str, ajuz: str) -> "VerseDraft":
        full = f"{sadr.strip()} ... {ajuz.strip()}"
        return cls(verse_number=verse_number, sadr=sadr.strip(), ajuz=ajuz.strip(), full_verse=full)


class VerseCritique(BaseModel):
    """Detailed evaluation of a single verse by the Critic Agent."""
    verse_number: int
    verse_text: str
    is_balanced: bool = False
    detected_meter: str = "غير محدد"
    meter_confidence: float = 0.0
    detected_rhyme: str = ""
    rhyme_matches_target: bool = False
    prosody_feedback: str = ""
    suggested_revision: Optional[str] = None


class CouncilCritiqueReport(BaseModel):
    """Overall assessment generated by the Poetic Critic Agent."""
    overall_quality_score: float = Field(ge=0.0, le=1.0)
    all_balanced: bool = False
    target_meter: str
    target_rhyme: str
    verse_critiques: List[VerseCritique] = Field(default_factory=list)
    general_notes: str = ""


class GeneratedPoem(BaseModel):
    """Final finished poem produced by the multi-agent council."""
    title: str
    topic: str
    theme: str
    meter: str
    meter_tafail: str
    rhyme: str
    verses: List[VerseDraft]
    iterations_used: int
    critique_report: CouncilCritiqueReport
    metaphor_sources: List[Dict[str, Any]] = Field(default_factory=list)
    full_text: str = ""
    safety_passed: bool = True
    safety_notes: Optional[str] = None

    def format_display(self) -> str:
        """Pretty-printed classical Arabic layout for display."""
        lines = [
            f"=== {self.title} ===",
            f"• الغرض الشعري : {self.theme}",
            f"• البحر العروضي : {self.meter} ({self.meter_tafail})",
            f"• القافية (الروي) : حرف {self.rhyme}",
            f"• جولات التنقيح  : {self.iterations_used} جولة تحكيم عروضي",
            "-" * 65
        ]
        for v in self.verses:
            lines.append(f"{v.sadr:<34}        {v.ajuz}")
        lines.append("-" * 65)
        if self.metaphor_sources:
            lines.append("• شواهد ومجازات من «أساس البلاغة»:")
            for m in self.metaphor_sources[:3]:
                lines.append(f"  - [{m.get('lemma', '')}] ({m.get('root', '')}): {m.get('metaphorical_meaning', '')[:120]}...")
        return "\n".join(lines)


class SingleVerseEvaluation(BaseModel):
    """Detailed diagnostic report for an individual verse submitted by a user."""
    verse_number: int
    sadr: str
    ajuz: str
    full_verse: str
    detected_meter: str
    meter_confidence: float
    is_meter_valid: bool
    sadr_meter: str
    ajuz_meter: str
    detected_rhyme: str
    is_rhyme_valid: bool
    prosodic_status: str
    defects: List[str] = Field(default_factory=list)
    remediation_suggestion: Optional[str] = None


class PoeticEvaluationReport(BaseModel):
    """Authoritative critique report for human-authored poetry, grounded in Mizan Al-Dhahab."""
    original_input: str
    total_verses: int
    dominant_meter: str
    meter_tafail: str
    meter_mnemonic_key: str
    dominant_rhyme: str
    sound_verses_count: int
    broken_verses_count: int
    overall_score: float = Field(ge=0.0, le=100.0)
    is_fully_sound: bool
    verse_evaluations: List[SingleVerseEvaluation] = Field(default_factory=list)
    poetic_defects_found: List[Dict[str, str]] = Field(default_factory=list)
    general_critique: str = ""
    rhetorical_analysis: str = ""
    remedy_recommendations: List[str] = Field(default_factory=list)
    reference_source: str = "ميزان الذهب في صناعة شعر العرب - أحمد الهاشمي"

    def format_display(self) -> str:
        """Pretty-printed evaluation report for display to the user."""
        status_symbol = "🌟 [قصيدة موزونة وسليمة العروض]" if self.is_fully_sound else "⚠️ [تنبيه: رُصد خلل أو كسر عروضي يحتاج تهذيباً]"
        lines = [
            "=" * 70,
            f"📜 تقرير التحكيم والنقد الشعري (مستند إلى «{self.reference_source}»)",
            f"{status_symbol}",
            f"• البحر العروضي الأغلب: {self.dominant_meter} ({self.meter_tafail})",
            f"• مفتاح البحر المنظوم: {self.meter_mnemonic_key}",
            f"• القافية والروي الملتزم: حرف ({self.dominant_rhyme})",
            f"• الدرجة العروضية العامة: {self.overall_score:.1f} / 100",
            f"• إحصاء الأبيات: {self.sound_verses_count} سليم موزون من أصل {self.total_verses}",
            "-" * 70,
            "🔍 التحليل التفصيلي للأبيات:"
        ]
        for v in self.verse_evaluations:
            mark = "✅" if v.is_meter_valid and v.is_rhyme_valid else "❌"
            lines.append(f"[{v.verse_number}] {v.sadr} ... {v.ajuz} {mark}")
            lines.append(f"    - الوزن: {v.prosodic_status} (البحر: {v.detected_meter} | ثقة: {v.meter_confidence:.0%})")
            lines.append(f"    - القافية: روي ({v.detected_rhyme})")
            if v.defects:
                lines.append(f"    - العيوب المرصودة: {', '.join(v.defects)}")
            if v.remediation_suggestion:
                lines.append(f"    - التصويب المقترح: {v.remediation_suggestion}")
        lines.append("-" * 70)
        if self.poetic_defects_found:
            lines.append("⚠️ تشخيص العيوب وفق «ميزان الذهب»:")
            for d in self.poetic_defects_found:
                lines.append(f"  • عيب [{d.get('name')}]: {d.get('definition')}")
                lines.append(f"    العلاج: {d.get('remedy')}")
            lines.append("-" * 70)
        if self.rhetorical_analysis:
            lines.append(f"🎨 النقد البياني والبلاغي:\n{self.rhetorical_analysis}")
            lines.append("-" * 70)
        if self.general_critique:
            lines.append(f"💡 خلاصة التحكيم والتوجيهات:\n{self.general_critique}")
            lines.append("=" * 70)
        return "\n".join(lines)
